Update tfsec.yml

diff --git a/.github/workflows/tfsec.yml b/.github/workflows/tfsec.yml
--- a/.github/workflows/tfsec.yml
+++ b/.github/workflows/tfsec.yml
@@ -27,17 +27,10 @@ jobs:
         uses: actions/checkout@v4
 
 
-      - name: Run tfsec (print to console and create SARIF)
-        uses: aquasecurity/tfsec-action@v1.0.0
-        with:
-          # --format lovely,sarif: Prints 'lovely' to console, creates 'sarif' file
-          # --out tfsec: Sets the base filename. tfsec adds '.sarif' automatically
-          additional_args: "--format lovely,sarif --out tfsec"
           
       - name: Run tfsec
         uses: aquasecurity/tfsec-sarif-action@21ded20e8ca120cd9d3d6ab04ef746477542a608
         with:
-          additional_args: "--format lovely,sarif --out tfsec"
           sarif_file: tfsec.sarif
 
       - name: Upload SARIF file
@@ -45,3 +38,16 @@ jobs:
         with:
           # Path to SARIF file relative to the root of the repository
           sarif_file: tfsec.sarif
+
+      - name: Fail build if issues found
+        run: |
+          # 'jq' is pre-installed on GitHub runners
+          # This command counts the number of 'results' in the SARIF file
+          RESULT_COUNT=$(jq '.runs[0].results | length' tfsec.sarif)
+          
+          if [ "$RESULT_COUNT" -gt 0 ]; then
+            echo "::error::Found $RESULT_COUNT vulnerabilities in tfsec.sarif. Failing the build."
+            exit 1
+          else
+            echo "No vulnerabilities found."
+          fi
